framework:
    messenger:
        buses:
            messenger.bus.default:
                # we have to disable the default middleware and explicitly
                # define the order as there is no priority option, just adding
                # our service to the middleware-option would add it before
                # send_middleware
                # @see https://github.com/symfony/symfony/issues/28568
                default_middleware: false
                middleware:
                    - {id: 'add_bus_name_stamp_middleware', arguments: ['messenger.bus.default']}
                    - reject_redelivered_message_middleware
                    - dispatch_after_current_bus
                    - failed_message_processing_middleware
                    - send_message
                    - handle_message
                    - Vrok\MessengerReply\ReplyMiddleware

        failure_transport: failed

# deactivated because of https://github.com/symfony/symfony/pull/37324 &
# https://github.com/symfony/symfony/issues/37414
#        serializer:
#            default_serializer: 'messenger.transport.symfony_serializer'
#            symfony_serializer:
#                format: json
#                context: { }

        transports:
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: pdf-service
                        type: direct
                        default_publish_routing_key: failed
                    queues:
                        failed:
                            binding_keys: [failed]

            input:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: pdf-service
                        type: direct
                        default_publish_routing_key: pdf-input
                    queues:
                        pdf-input:
                            binding_keys: [pdf-input]
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            output:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: pdf-service
                        type: direct
                        default_publish_routing_key: pdf-output
                    queues:
                        pdf-output:
                            binding_keys: [pdf-output]
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

        routing:
            # '*' catches all messages, even when they are also routed otherwise
            #'*': output
            'Vrok\PdfService\Contracts\GeneratePdfMessage': input
            'Vrok\PdfService\Contracts\PdfResultMessage': output
            'Symfony\Component\Mailer\Messenger\SendEmailMessage':  input
