monolog:
    handlers:
        main:
            type: buffer
            handler: grouped
            channels: [app]
            level: debug
            bubble: false
        default:
            type: buffer
            handler: grouped
            channels: ["!app", "!event"]
            level: error
            bubble: false
        grouped:
            type: whatfailuregroup
            members: [streamed, logstash]
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            include_stacktraces: true
        logstash:
            type: gelf
            level: debug
            publisher:
                hostname: '%env(GELF_SERVER)%'
                port: '%env(GELF_PORT)%'
                chunk_size: 8154
            include_stacktraces: true
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
