version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 8090:15672
    environment:
      RABBITMQ_DEFAULT_USER: messenger
      RABBITMQ_DEFAULT_PASS: messenger

  pdf-php:
    build: php
    container_name: pdf-php
    links:
      - rabbitmq
    volumes:
      - ../:/var/www/html
    environment:
      APP_ENV: test
      XDEBUG_CONFIG: remote_host=host.docker.internal
